// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ITeleporterMessenger$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ITeleporterMessenger";
  readonly sourceName: "contracts/interfaces/ITeleporterMessenger.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"destinationBlockchainID","type":"bytes32"},{"internalType":"address","name":"destination","type":"address"},{"internalType":"uint256","name":"requestId","type":"uint256"},{"internalType":"bytes32","name":"answerHash","type":"bytes32"}],"name":"sendCrossChainAnswer","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ITeleporterMessenger.sol";
  readonly buildInfoId: "solc-0_8_20-49ddc97f78736bec0c762c83544c7ce0e22ad3d4";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ITeleporterMessenger"]: ITeleporterMessenger$Type;
    ["contracts/interfaces/ITeleporterMessenger.sol:ITeleporterMessenger"]: ITeleporterMessenger$Type;
  }
}