// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ITeleporterReceiver$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ITeleporterReceiver";
  readonly sourceName: "contracts/interfaces/ITeleporterReceiver.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"sourceBlockchainID","type":"bytes32"},{"internalType":"address","name":"originSenderAddress","type":"address"},{"internalType":"bytes","name":"message","type":"bytes"}],"name":"receiveTeleporterMessage","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ITeleporterReceiver.sol";
  readonly buildInfoId: "solc-0_8_20-49ddc97f78736bec0c762c83544c7ce0e22ad3d4";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ITeleporterReceiver"]: ITeleporterReceiver$Type;
    ["contracts/interfaces/ITeleporterReceiver.sol:ITeleporterReceiver"]: ITeleporterReceiver$Type;
  }
}