/* Neural Hive page scripts: agents list (table), agent detail, execution details, add agent. */
(function(){
  var N=window.NH; var page=document.body.getAttribute("data-page"); var walletState=N.wallet; var PAY=null;
  function D(id){ return document.getElementById(id); }
  function el(tag,cls,text){ var e=document.createElement(tag); if(cls){ e.className=cls; } if(text!=null){ e.textContent=text; } return e; }
  function notice(msg,bad){ var k=null; if(!bad && msg && /^(Agent .* is LIVE|Owner wallet connected|Withdrew |Price updated)/.test(msg)){ k="ok"; } return N.notify(msg,bad,k); }
  function mdNode(text,cls){ var d=el("div","nh-prose"+(cls?" "+cls:"")); d.innerHTML=N.md(N.str(text)); return d; }
  function tag(text,cls){ return el("span","nh-tag"+(cls?" "+cls:""),text); }
  function tagsCell(list){ var d=el("div"); if(!list||!list.length){ d.appendChild(tag("none","mut")); return d; } for(var i=0;i<list.length;i++){ d.appendChild(tag(list[i])); } return d; }

  function th(text){ return el("th",null,text); } function td(text,cls){ return el("td",cls,text); }
  function pageAgents(){ N.get("/agents").then(function(d){ var list=d.agents||[]; if(D("count")){ D("count").textContent=list.length+" agents ("+(d.online||0)+" online)"; } var box=D("agentGrid"); if(!box){ return; } box.textContent=""; if(!list.length){ box.appendChild(el("div","nh-muted","No agents registered.")); return; } var wrap=el("div","nh-table-wrap"); var table=el("table","nh-table"); var thead=el("thead"); var hr=el("tr"); ["ID","Name","Status","Tags","On-chain contract (id)","Balance","Price","Provider / Model","Reputation","Risk","Executions","Avg latency",""].forEach(function(h){ hr.appendChild(th(h)); }); thead.appendChild(hr); table.appendChild(thead); var tb=el("tbody"); for(var i=0;i<list.length;i++){ var a=list[i]; var tr=el("tr"); tr.appendChild(td(a.id)); tr.appendChild(td(a.name||a.id)); var st=el("td"); st.appendChild(tag(a.status==="online"?"live":(a.status||"offline"),a.status==="online"?"ok":"bad")); tr.appendChild(st); var tg=el("td"); tg.appendChild(tagsCell(a.tags)); tr.appendChild(tg); var oc=el("td"); if(a.contractId){ var ocl=el("span","nh-mono",a.contractId); ocl.title=a.contractId; oc.appendChild(ocl); } else { oc.appendChild(el("span","nh-muted","-")); } tr.appendChild(oc); var bl=el("td"); bl.appendChild(el("span","nh-bal",(a.balanceHive!=null?(a.balanceHive+" HIVE"):"0 HIVE"))); tr.appendChild(bl); tr.appendChild(td(a.endpoint||"-")); tr.appendChild(td(a.priceHive!=null?(a.priceHive+" HIVE"):"unset")); tr.appendChild(td((a.provider||"-")+" / "+(a.model||"-"))); tr.appendChild(td(N.fmt(a.reputation,3))); tr.appendChild(td(N.fmt(a.risk,3))); tr.appendChild(td(String(a.executions||0)+" (ok "+(a.success||0)+" / fail "+(a.failure||0)+")")); tr.appendChild(td(a.avgLatencyMs==null?"-":(a.avgLatencyMs+" ms"))); var act=el("td"); var link=el("a","btn","Details"); link.href="/agent.html?id="+encodeURIComponent(a.id); act.appendChild(link); tr.appendChild(act); tb.appendChild(tr); } table.appendChild(tb); wrap.appendChild(table); box.appendChild(wrap); }).catch(function(e){ notice(N.errText(e),true); }); }

  function pageAgent(){ var id=N.qs("id"); var box=D("agentBox"); if(!id){ if(box){ box.appendChild(el("div","nh-muted","No agent id supplied. Open this page from the agent list.")); } notice("No agent id supplied. Open this page from the agent list.",true); return; } N.get("/agents/"+encodeURIComponent(id)).then(function(a){ if(a.error){ throw new Error(a.error); } if(!box){ return; } box.textContent=""; var card=el("div","nh-card"); var head=el("div"); head.style.display="flex"; head.style.gap="10px"; head.style.alignItems="center"; head.appendChild(el("span","dot "+(a.status==="online"?"ok":"bad"))); head.appendChild(el("b",null,a.name||a.id)); head.appendChild(tag("id: "+a.id)); head.appendChild(tag(a.status||"unknown",a.status==="online"?"ok":"bad")); card.appendChild(head); var kv=el("div","nh-kv"); kv.style.marginTop="12px"; function row(k,v){ kv.appendChild(el("div","k",k)); kv.appendChild(el("div","v",(v==null?"-":String(v)))); } row("id",a.id); row("name",a.name||a.id); row("endpoint",a.endpoint||"-"); row("on-chain contract (unique id)",a.contractId||"(deploying...)"); row("contract balance",(a.balanceHive!=null?(a.balanceHive+" HIVE"):"0 HIVE")); row("price",a.priceHive!=null?(a.priceHive+" HIVE/query"):"unset"); row("provider / model",(a.provider||"-")+" / "+(a.model||"-")); row("reputation / risk",N.fmt(a.reputation,3)+" / "+N.fmt(a.risk,3)); row("executions",a.executions+" (ok "+a.success+" / fail "+a.failure+")"); row("avg latency",(a.avgLatencyMs==null?"-":(a.avgLatencyMs+" ms"))); if(a.lastError){ row("last error",a.lastError); } row("owner",a.owner||"(hub/deployer)"); card.appendChild(kv); var tg=el("div"); tg.style.marginTop="10px"; tg.appendChild(tagsCell(a.tags)); card.appendChild(tg); box.appendChild(card); var pi=D("priceInput"); if(pi){ pi.value=(a.priceHive!=null?a.priceHive:""); } var lb=D("agentIdLabel"); if(lb){ lb.textContent=a.id; } var pb=D("priceBtn"); if(pb){ pb.onclick=function(){ setPrice(a.id); }; } renderAgentWallet(a.id); }).catch(function(e){ notice(N.errText(e),true); if(box){ box.textContent=""; box.appendChild(el("div","nh-muted","Could not load agent "+id+": "+N.errText(e))); } }); }
  function renderAgentWallet(id){ var box=D("agentBox"); if(!box){ return; } var prev=D("agentWalletCard"); if(prev&&prev.parentNode){ prev.parentNode.removeChild(prev); } N.get("/agents/"+encodeURIComponent(id)+"/wallet").then(function(w){ if(!w||w.error){ return; } var card=el("div","nh-card"); card.id="agentWalletCard"; card.appendChild(el("h2","nh-h2","Agent wallet (HIVE smart contract)")); card.appendChild(el("div","nh-muted","Each agent has its own on-chain wallet holding the HIVE it earned. The owner can withdraw it to their MetaMask address.")); var kv=el("div","nh-kv"); kv.style.marginTop="10px"; function row(k,v){ kv.appendChild(el("div","k",k)); kv.appendChild(el("div","v",(v==null?"-":String(v)))); } row("wallet",w.wallet||"-"); row("balance",(w.balanceHive!=null?w.balanceHive:"0")+" HIVE"); row("owner",w.owner||"(hub/deployer)"); card.appendChild(kv); var btn=el("button","nh-btn primary","Withdraw to owner wallet"); btn.style.marginTop="12px"; btn.onclick=function(){ withdrawAgent(id); }; card.appendChild(btn); var out=el("pre"); out.style.marginTop="10px"; out.style.whiteSpace="pre-wrap"; out.style.fontSize="11.5px"; out.style.color="var(--muted)"; out.id="walletOut"; card.appendChild(out); box.appendChild(card); }).catch(function(){}); }
  function withdrawAgent(id){ notice(""); N.connect().then(function(){ var acct=N.wallet.account; notice("Preparing the on-chain withdraw for "+acct+"...",false); return N.post("/agents/"+encodeURIComponent(id)+"/withdraw", { owner:acct, from:acct }); }).then(function(wd){ if(!wd.__ok||wd.error){ throw new Error(wd.error||("HTTP "+wd.__status)); } var acct=N.wallet.account; if(wd.owner && acct && String(wd.owner).toLowerCase()!==String(acct).toLowerCase()){ throw new Error("Only the agent owner ("+wd.owner+") can withdraw. Connect that wallet (the deployer owns the seed agents)."); } notice("Confirm the withdraw() transaction in MetaMask - the agent contract sends its HIVE to you.",false); return N.sendTx(wd.contract||wd.to, wd.data).then(function(tx){ return N.post("/agents/"+encodeURIComponent(id)+"/withdraw", { owner:acct, from:acct, txHash:tx }); }); }).then(function(d){ if(!d.__ok||d.error){ throw new Error(d.error||("HTTP "+d.__status)); } var o=D("walletOut"); if(o){ o.textContent=JSON.stringify(d,null,2); } notice("Withdrew "+(d.balanceHive||"0")+" HIVE from the agent contract "+(d.wallet||d.contract||"")+" to the owner (tx "+(d.txHash||"-")+").",false); setTimeout(function(){ renderAgentWallet(id); },600); }).catch(function(e){ notice(N.errText(e),true); }); }
  function setPrice(id){ var v=parseFloat(D("priceInput").value); if(isNaN(v)||v<0){ notice("Enter a non-negative price in HIVE.",true); return; } notice(""); return N.connect().then(function(){ return N.get("/agents/"+encodeURIComponent(id)); }).then(function(a){ var owner=(a.owner||""); var acct=(window.NH.wallet.account||""); if(owner && acct && owner.toLowerCase()!==acct.toLowerCase()){ throw new Error("Only the agent owner ("+owner+") can update this price. Connect that wallet (the deployer owns the seed agents)."); } var wei=(BigInt(Math.round(v*1e6))*BigInt(1000000000000)).toString(); notice("Confirm the updatePrice transaction in MetaMask - the owner pays gas.",false); return N.updateAgentPrice(a.registry||N.pay().registry, wei).then(function(tx){ return N.post("/agents/"+encodeURIComponent(id)+"/price", { priceHive:v, txHash:tx, from:acct }); }); }).then(function(d){ if(!d.__ok||d.error){ throw new Error(d.error||("HTTP "+d.__status)); } notice("Price updated to "+v+" HIVE on chain and in the router.",false); if(D("onchainBox")){ D("onchainBox").textContent=JSON.stringify((d.onchain||{}),null,2); } pageAgent(); }).catch(function(e){ notice(N.errText(e),true); }); }

  function subText(subs,s,i){ var m=null; for(var k=0;k<(subs||[]).length;k++){ var x=subs[k]||{}; if((x.id||x.subtaskId)===s.subtaskId){ m=x; break; } } if(!m){ m=(subs||[])[i]; } if(!m||typeof m!=="object"){ return (typeof m==="string")?m:""; } var t=m.text||m.task||m.query||m.prompt||m.description||m.content||m.question||""; return (typeof t==="string")?t:""; }
  function kvLine(parent,k,v){ var kv=el("div","nh-kv"); kv.appendChild(el("div","k",k)); kv.appendChild(el("div","v",(v==null?"-":String(v)))); parent.appendChild(kv); return kv; }
  function pageExecution(){ var id=N.qs("id"); var box=D("exec"); if(!id){ if(box){ box.textContent="No execution id supplied."; } notice("No execution id supplied.",true); return; } Promise.all([ N.get("/trace/"+encodeURIComponent(id)), N.get("/events/"+encodeURIComponent(id)) ]).then(function(rr){ var res=rr[0]; var events=((rr[1]||{}).events)||[]; if(res.error){ throw new Error(res.error); } if(D("title")){ if(res.task){ D("title").innerHTML=N.md(N.str(res.task)); } else { D("title").textContent="Execution details"; } } if(D("sub")){ D("sub").textContent=res.taskId; } renderExec(res,events); }).catch(function(e){ notice(N.errText(e),true); if(box){ box.textContent="Could not load execution "+id+": "+N.errText(e); } }); }
  function renderExec(res,events){ var a=res.algorithms||{}; var c=res.cost||{}; var box=D("exec"); if(!box){ return; } box.textContent=""; var card=el("div","nh-card"); card.appendChild(el("div","nh-h2","How the Hub decomposed the query")); card.appendChild(mdNode(res.task,"nh-task")); kvLine(card,"task id",res.taskId); kvLine(card,"complexity",(res.complexity||{}).level); kvLine(card,"routing",a.routeModeUsed||a.routing); kvLine(card,"aggregation",a.aggregation); kvLine(card,"expected cost",(c.totalHive||"-")+" HIVE"); box.appendChild(card);
    var c2=el("div","nh-card"); c2.appendChild(el("div","nh-h2","Routing graph")); var un=el("div","nh-node"); un.appendChild(el("b",null,"USER REQUEST")); un.appendChild(mdNode(res.task,"nh-in-node")); c2.appendChild(un); c2.appendChild(el("div","nh-arrow","v")); c2.appendChild(el("div","nh-node","HUB decompose then route ("+(a.routeModeUsed||a.routing)+") then aggregate ("+a.aggregation+")")); var sels=res.selections||[]; var subs=res.subtasks||[]; for(var i=0;i<sels.length;i++){ var s=sels[i]; c2.appendChild(el("div","nh-arrow","v")); var sn=el("div","nh-node"); sn.appendChild(el("b",null,s.subtaskId+" to agent "+s.agentId+" ("+s.priceHive+" HIVE)")); var st=subText(subs,s,i); if(st){ sn.appendChild(mdNode(st,"nh-in-node")); } c2.appendChild(sn); } c2.appendChild(el("div","nh-arrow","v")); c2.appendChild(el("div","nh-node","FINAL RESPONSE")); box.appendChild(c2);
    var c3=el("div","nh-card"); c3.appendChild(el("div","nh-h2","Agent replies")); var results=res.agentResults||[]; for(var j=0;j<results.length;j++){ var r=results[j]; var rn=el("div","nh-node"); rn.appendChild(el("b",null,(r.agentName||r.agentId)+" :"+r.port+" "+(r.model||"")+" "+(r.latencyMs||0)+" ms")); var rt=r.answer||r.reply||r.response||r.output||r.text||r.content; if(rt&&typeof rt==="string"){ rn.appendChild(mdNode(rt,"nh-in-node")); } c3.appendChild(rn); } box.appendChild(c3);
    var c4=el("div","nh-card"); c4.appendChild(el("div","nh-h2","Aggregation")); var ag=res.aggregation||{}; kvLine(c4,"rule",a.aggregation); kvLine(c4,"committee kept",String(ag.inputs)); if(a.krumKeep!=null){ kvLine(c4,"(krum kept / outliers)",a.krumKeep+" / "+(a.krumOutliers!=null?a.krumOutliers:"-")); } if(a.aggregatorNote){ kvLine(c4,"aggregation note",a.aggregatorNote); } kvLine(c4,"status",ag.ok?"ok":("failed: "+(ag.error||"-"))); var prose=el("div","nh-prose"); prose.innerHTML=N.md(res.answer||""); c4.appendChild(prose); box.appendChild(c4);
    var c5=el("div","nh-card"); c5.appendChild(el("div","nh-h2","On-chain evidence")); var an=res.anchor||{}; kvLine(c5,"answer hash",res.answerHash); kvLine(c5,"anchored",an.ok?"yes":"no"); kvLine(c5,"request tx",an.requestTx||"-"); kvLine(c5,"settlement tx",an.settleTx||"-"); kvLine(c5,"network",an.network||"-"); box.appendChild(c5);
    if(res.payment){ var p=res.payment; var c6=el("div","nh-card"); c6.appendChild(el("div","nh-h2","HIVE payment")); kvLine(c6,"mode",p.mode); kvLine(c6,"paid",(p.paidHive||"0")+" HIVE"); kvLine(c6,"payer",p.payer||"-"); kvLine(c6,"tx",p.txHash||"-"); box.appendChild(c6); }
    }

  function pageAddAgent(){ var sb=D("submit"); if(sb){ sb.onclick=registerAgent; } var ob=D("ownerBtn"); if(ob){ ob.onclick=connectOwner; } N.loadPay().then(function(c){ PAY=c; var ci=D("chainInfo"); if(ci){ ci.textContent="chain "+c.chainId+" "+c.rpcUrl; } var fee=D("feeInfo"); if(fee){ fee.textContent=(c.registrationFeeHive!=null?c.registrationFeeHive:"-")+" HIVE registration fee (configurable)"; } }); if(N.eth()){ N.rpc("eth_accounts").then(function(a){ if(a&&a.length){ walletState.account=a[0]; showOwner(); } }).catch(function(){}); } }
  function connectOwner(){ notice(""); N.connect().then(function(){ showOwner(); notice("Owner wallet connected.",false); }).catch(function(e){ notice(N.errText(e),true); }); }
  function showOwner(){ var ob=D("ownerBtn"); if(ob){ ob.textContent=N.shortAddr(walletState.account); } }
  function registerAgent(){ notice(""); var res=D("result"); if(res){ res.textContent=""; } var name=D("name").value.trim(); var endpoint=D("endpoint").value.trim(); var price=parseFloat(D("price").value||"0"); var tags=D("tags").value.split(",").map(function(s){ return s.trim().toLowerCase(); }).filter(function(s){ return s; }); var type=D("type").value; if(!name||!endpoint){ notice("Name and endpoint are required.",true); return; } N.connect().then(function(){ showOwner(); notice("Verifying the agent and requesting the HIVE registration payment...",false); return N.post("/agents/register", { name:name, endpoint:endpoint, priceHive:isNaN(price)?0:price, tags:tags, type:type, owner:(walletState.account||""), signer:(walletState.account||"") }); }).then(function(d){ if(!d.__ok||d.error){ throw new Error(d.error||("HTTP "+d.__status)); } if(d.payment && d.payment.treasury && d.payment.costWei){ notice("Confirm the "+(d.payment.costHive||"-")+" HIVE registration fee in MetaMask",false); return N.transferHive(d.payment.treasury, d.payment.costWei).then(function(tx){ return N.post("/agents/register/confirm", { id:d.id, registrationId:d.registrationId, txHash:tx }); }); } return d; }).then(function(d){ if(res){ res.textContent=""; res.appendChild(el("b",null,"Status: "+(d.status||"unknown"))); res.appendChild(el("div","nh-muted",d.detail||"")); res.appendChild(el("div","nh-muted","Agent id: "+(d.id||"-"))); } if(d.ok){ notice("Agent "+name+" is LIVE and registered on-chain.",false); } else { notice("The agent did not pass liveness/registration: "+(d.detail||""),true); } var cb=D("calldataBox"); if(cb){ cb.textContent=JSON.stringify((d.onchain||{}),null,2); } }).catch(function(e){ notice(N.errText(e),true); }); }
  function init(){ if(page==="agents"){ pageAgents(); } else if(page==="agent"){ pageAgent(); } else if(page==="execution"){ pageExecution(); } else if(page==="add-agent"){ pageAddAgent(); } if(D("walletBtn")){ N.mountWallet("walletBtn"); } }
  if(document.readyState==="loading"){ document.addEventListener("DOMContentLoaded",init); } else { init(); }
})();

